# Generated by Django 3.2.8 on 2021-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(max_length=256, null=True, verbose_name='유저 주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_comp_address',
            field=models.CharField(max_length=256, null=True, verbose_name='업체 주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_comp_name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='업체 이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pet_num',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='동물 번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone_num',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='유저 연락처'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_vet_num',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='수의사 번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='유저 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='유저 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='유저 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pw',
            field=models.CharField(max_length=128, null=True, verbose_name='유저 비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_register_dttm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='계정 생성시간'),
        ),
    ]
