# Generated by Django 3.2.8 on 2021-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(default='Free', max_length=32, verbose_name='게시판 종류'),
        ),
    ]
